2021-01-28 16:37:55,805 INFO    MainThread:28739 [wandb_setup.py:_flush():70] setting env: {}
2021-01-28 16:37:55,805 INFO    MainThread:28739 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-28 16:37:55,805 INFO    MainThread:28739 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-28 16:37:55,805 INFO    MainThread:28739 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-28 16:37:55,805 INFO    MainThread:28739 [wandb_init.py:_log_setup():318] Logging user logs to /home/iiitd/Desktop/Ahmad/doa1/wandb/run-20210128_163755-3aiw2kk7/logs/debug.log
2021-01-28 16:37:55,805 INFO    MainThread:28739 [wandb_init.py:_log_setup():319] Logging internal logs to /home/iiitd/Desktop/Ahmad/doa1/wandb/run-20210128_163755-3aiw2kk7/logs/debug-internal.log
2021-01-28 16:37:58,000 WARNING MainThread:28739 [wandb_init.py:init():638] interrupted
Traceback (most recent call last):
  File "/home/iiitd/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 618, in init
    run = wi.init()
  File "/home/iiitd/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 469, in init
    _ = backend.interface.communicate_run_start()
  File "/home/iiitd/anaconda3/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 641, in communicate_run_start
    result = self._communicate(rec)
  File "/home/iiitd/anaconda3/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 463, in _communicate
    f = future.get(timeout)
  File "/home/iiitd/anaconda3/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 63, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/iiitd/anaconda3/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/iiitd/anaconda3/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2021-01-28 16:37:58,031 INFO    MainThread:28739 [internal.py:handle_exit():139] Internal process exited
